In [1]:
import pandas as pd
import numpy as np

In [7]:
pd_data = pd.read_excel('./files/advertising.xls')
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Daily Time Spent on Site  1000 non-null   float64       
 1   Age                       1000 non-null   int64         
 2   Area Income               1000 non-null   float64       
 3   Daily Internet Usage      1000 non-null   float64       
 4   Ad Topic Line             1000 non-null   object        
 5   City                      1000 non-null   object        
 6   Male                      1000 non-null   int64         
 7   Country                   1000 non-null   object        
 8   Timestamp                 1000 non-null   datetime64[ns]
 9   Clicked on Ad             1000 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 78.2+ KB


In [9]:
x = pd_data[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male']]
y = pd_data[['Clicked on Ad']]
x.shape, y.shape

((1000, 5), (1000, 1))

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((750, 5), (250, 5), (750, 1), (250, 1))

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
log = LogisticRegression() 

In [22]:
log.fit(x_train, y_train)

c:\users\jeaung-lee\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [23]:
log.coef_, log.intercept_

(array([[-5.95215000e-02,  2.59065365e-01, -2.13797683e-05,
         -2.27189364e-02,  1.76458739e-03]]),
 array([0.00532073]))

In [24]:
log.predict_proba(x_train[100:104])

array([[0.03238474, 0.96761526],
       [0.00338799, 0.99661201],
       [0.01966142, 0.98033858],
       [0.95222482, 0.04777518]])

In [25]:
log.predict(x_train[100:104])

array([1, 1, 1, 0], dtype=int64)

In [26]:
from sklearn import metrics

In [27]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((750,), (750, 1))

In [28]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91       387
           1       0.93      0.86      0.89       363

    accuracy                           0.90       750
   macro avg       0.90      0.90      0.90       750
weighted avg       0.90      0.90      0.90       750



In [29]:
metrics.confusion_matrix(y_train, y_pred)

array([[363,  24],
       [ 50, 313]], dtype=int64)

In [30]:
import pickle

In [31]:
pickle.dump(log, open('./saves/log.pkl', 'wb'))

In [33]:
log_load = pickle.load(open('./saves/log.pkl', 'rb'))